# Site settings
title: decaywood's Blog
SEOTitle: decaywood's Blog
header-img: img/home-bg.jpg
email: decaywood@qq.com
description: "Hi, I'm decaywood"
keywords: "Java Python Javascript..."
github-source: https://github.com/decaywood/decaywood.github.io
url: http://blog.decaywood.me
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# CDN Accelerate
cdnurl: http://7xppt1.com1.z0.glb.clouddn.com
#cdnurl: ""
#debug: true

# Build settings
permalink: pretty
paginate: 20
exclude: ["less","node_modules","Gruntfile.js","package.json","decaywood.github.io.iml", "_posts/2016-01-02-copy-me.markdown"]

post-img-count: 70

# nessessary in Mac OS
gems: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown

kramdown:
  input: GFM                            # use Github Flavored Markdown !important


# social settings

#Disqus settings
#disqus_username: _your_disqus_short_name_

# Duoshuo settings
duoshuo_username: decaywood
# Share component is depend on Comment so we can NOT use share only.
duoshuo_share: true                     # set to false if you want to use Comment without Sharing

# SNS settings
RSS: true
#weibo_username:     decaywood
#zhihu_username:     decaywood
github_username:    decaywood
lofter_username:    decaywood
v2ex_username:      decaywood
#twitter_username:  decaywood
#facebook_username:  decaywood




# Analytics settings
# Baidu Analytics
ba_track_id: 8cfd62dcadd7b6214b39961e11bb6981
# Google Analytics
#ga_track_id:  # Format: UA-xxxxxx-xx
#ga_domain: # decaywood.github.io
51la_track_id: 18749763

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: coding... refactoring... sharing...
sidebar-avatar: img/avatar-decaywood.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 0             # A tag will be featured if the size of it is more than this condition value
